admittance_controller:
  type: admittance_controller/AdmittanceController
  ik_timeout: 0.1
  ik_tolerance: 6.28319
  loop_frequency: 1000
  sp_tolerance: 0.01
  mass_matrix: [1.0, 1.0, 0.001]
  damping_matrix: [900.0, 900.0, 5000]
  stiffness_matrix: [1300.0, 1300.0, 90.0]